class MsgType:
    GAME_LIST = "game_list"
    ROOM      = "room"
    STATE     = "state"
    REQUEST   = "request"
    LOG       = "log"
    ERROR     = "error"
    GAME_OVER = "game_over"
    PONG      = "pong"
    LIST      = "list"
    CREATE    = "create"
    JOIN      = "join"
    RESPONSE  = "response"
    PING      = "ping"

class ErrorCode:
    WRONG_PASSWORD = "wrong_password"
    ROOM_NOT_FOUND = "room_not_found"
    ROOM_FULL      = "room_full"
    GAME_STARTED   = "game_started"
    INVALID_MSG    = "invalid_msg"
    NOT_YOUR_TURN  = "not_your_turn"
